//------------------------------------------------------------------------
// Copyright(c) 2024 Hikari Audio.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"mu-law.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"mu-law VST3 (64Bit)"
#else
#define stringFileDescription	"mu-law VST3"
#endif
#define stringCompanyName		"Hikari Audio\0"
#define stringLegalCopyright	"Copyright(c) 2024 Hikari Audio."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
